config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'users/registrations'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    get '/', to: "tops#index"
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :artists, only: [:index, :show, :create, :edit, :update, :destroy]
    resources :genres, only: [:index, :show, :create, :edit, :update, :destroy]
    resources :labels, only: [:index, :show, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show,  :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update, :destroy]
    resources :contacts, only: [:index, :show, :update]
  end

  scope module: :user do
    root to: "genres#index"
    resources :genres, only: [:show]
    resources :searches, only: [:index, :create]
    resources :songs, only: [:show]
    resources :orders, only: [:index, :new, :create, :update]
    resource :mypages, only: [:show, :edit, :new, :create, :update, :destroy]
    resources :carts, only: [:index, :update, :destroy]
    resource :contacts, only: [:new, :create]
    post 'products/:id/add', to: "products#add", as: "add_cartdetail"
    patch 'mypages/info', to: 'mypages#create_info'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :discs, dependent: :destroy
  has_many :track_relations, through: :discs, dependent: :destroy
  has_many :songs, through: :track_relations
  accepts_nested_attributes_for :discs, allow_destroy: true
  accepts_nested_attributes_for :track_relations, allow_destroy: true
  accepts_nested_attributes_for :songs
  belongs_to :label
  belongs_to :genre
  has_many :cart_details
  has_many :order_details
  attachment :image


  validates :name, presence: true, length: {in: 1..255}
  validates :price, presence: true, numericality: {greater_than: 0}
  validates :stock, presence: true, numericality: {greater_than_or_equal_to: 0}
  validates :product_type, presence: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::Base
  before_action :authenticate_user!
  authorize_resource
  def index
    @products = Product.page(params[:page]).per(20)
  end

  def new
    @artists = Artist.all
    @genres = Genre.all
    @labels = Label.all
    @songs = Song.all

    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path
    else
      @artists = Artist.all
      @genres = Genre.all
      @labels = Label.all
      @songs = Song.all
      render "new" 
    end
  end

  def edit
    @artists = Artist.all
    @genres = Genre.all
    @labels = Label.all
    @songs = Song.all

    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if params[:request]
      stock = @product.stock.to_i + params[:request].to_i
      if @product.update(stock: stock.to_i)
        redirect_to admin_products_path
      else
        redirect_to admin_products_path
      end
    else
      if @product.update(product_params)
        redirect_to admin_products_path
      else
        redirect_to edit_admin_product_path(@product.id), alert: @product.errors.full_messages
      end
    end
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy!
    redirect_to admin_products_path
  end

  private
  def product_params
    params.require(:product).permit(
      :id, :name, :image, :product_type, :label_id, :genre_id, :price, :release_date,
      discs_attributes: [
        :id, :disc_order, :_destroy,
        track_relations_attributes: [
          :id, :song_id, :disk_id, :track_order,  :_destroy,
          song_attributes: [
            :id, :name, :file, :artist_id,  :recommend_level, :file_cache, :remove_file
          ]
        ]
      ]
    )
  end

end

app/controllers/user/products_controller.rb
class User::ProductsController < User::Base
	before_action :authenticate_user!
	def add
		if CartDetail.where(user_id: current_user.id, product_id: params[:id]).present?
			flash[:notice] = "カート内に既に存在しています"
			redirect_to carts_path
		else
			cartd = CartDetail.new(cartd_params)
			cartd.user_id = current_user.id
			cartd.product_id = params[:id]
			if cartd.save
				cartd.product.stock -= cartd.number
				redirect_to carts_path
			else
				redirect_to root_path
			end
		end
 	end

 	private
 		def cartd_params
 			params.permit(:number)
 		end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
    def link_to_add_field(name, f, association, options={})
        new_object = f.object.class.reflect_on_association(association).klass.new
        id = new_object.object_id
        fields = f.fields_for(association, new_object, child_index: id) do |builder|
            if association == "discs"
                render(association.to_s.singularize + "_form", f: builder, d: new_object)
            else
                render(association.to_s.singularize + "_form", f: builder)
            end
        end
        link_to(name, '#', class: "btn btn-primary add_field", data: {association: association, id: id, fields: fields.gsub("\n","")})
    end
    
    def new_song_field(f, association, options={})
        new_object = f.object.class.reflect_on_association(association).klass.new
        id = new_object.object_id
        f.fields_for(association, new_object, child_index: id) do |builder|
            render("song_form", f: builder)
        end
    end

    def select_song_field(name, f, association, mode, options={})
        new_object = f.object.class.reflect_on_association(association).klass.new
        id = new_object.object_id

        new_fields = f.fields_for(association, new_object, child_index: id) do |builder|
            render("song_form", f: builder)
        end

        select_fields = render("select_song_form", f: f)

        link_to(name, '#', class: "btn btn-default change-mode", data: {mode: mode, id: id, new: new_fields.gsub("\n",""), exist: select_fields.gsub("\n", "")})
    end

    def link_to_remove_field(name, f, association, options={})
        # _destroy の hiddenフィールドと削除ボタンを設置
        f.hidden_field(:_destroy) + link_to(name, '#', class: "remove_field btn btn-danger", data: {association: association})
    end
end

app/helpers/user/products_helper.rb
module User::ProductsHelper
end

app/views/admin/products/_disc_form.html.erb
<div class="new-disc-form">
    <div class='form-group'>
        <div class='col-xs-1'>
            <%= f.label :disc_order, "Disc", class:'control-label pull-right' %>
        </div>
        <div class='col-xs-1'>
            <%= f.number_field :disc_order, class: 'form-control' %>
        </div>
        <div class='col-xs-8'></div>
        <div class='col-xs-2'>
            <%= link_to_remove_field("remove disc", f, :discs, {})%>
        </div>
    </div>
    <%= link_to_add_field("track add", f, :track_relations, {}) %>

    <table class="table">
        <thead>
            <th>トラック番号</th>
            <th>アーティスト</th>
            <th>楽曲ファイル/名</th>
        </thead>
        <tbody>
            <% f.object.track_relations.each do |tr| %>
                <%= f.fields_for :track_relations, tr, child_index: tr.object_id do |builder| %>
                    <%= render "admin/products/track_relation_form", f: builder %>
                <% end %>
            <% end %>
        </tbody>
    </table>
</div>

app/views/admin/products/_product_list.html.erb
<div class="row">
    <h2>商品一覧</h2>
    <%= link_to "新規商品追加", new_admin_product_path, class: "btn btn-default pull-right" %>
    <table class="table">
        <thead>
            <th>ジャケット</th>
            <th>商品名</th>
            <th>Stock</th>
            <th></th>
            <th></th>
            <th></th>
        </thead>
        <tbody>
            <% products.each do |p| %>
                <tr>
                    <td class="col-xs-1"><%= attachment_image_tag p, :image, class: "img-thumbnail", fallback: "no_image.png", size: "50x50"%></td>
                    <td class="col-xs-2 table-text-contents"><%= p.name %></td>
                    <td class="col-xs-1 table-text-contents"><%= p.stock %>枚</td>
                    <td class="col-xs-4">
                        <%= form_with url: admin_product_path(p), method: :patch do |f| %>
                            <div class="col-xs-5">
                                <div class="input-group">
                                    <%= f.number_field :request, placeholder: 10, class: "form-control", min: 1, max: 100 %>
                                    <span class="input-group-addon">枚</span>
                                </div>
                            </div>
                            <div class="col-xs-7">
                                <%= f.submit "発注", class: "btn btn-default","data-confirm"=>"発注すると3日経過して、届いたことになります。" %>
                            </div>
                        <% end %>
                    </td>
                    <td class="col-xs-1"><%= link_to "編集", edit_admin_product_path(p.id), class: "btn btn-success" %></td>
                    <td class="col-xs-1"><%= link_to "削除", admin_product_path(p.id), method: :delete, class: "btn btn-danger", "data-confirm" => "この商品を本当に削除しますか?" %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <%= paginate products, class: "paginate" %>
</div>

app/views/admin/products/_select_song_form.erb
<td class='song-form'></td>
<td class='song-form col-xs-3'>
    <%= f.select :song_id, @songs.map{|s| [s.artist.name+" - "+s.name, s.id]},{}, class: 'form-control'  %>
</td>
<td class='song-form'></td>
<td class='song-form'></td>

app/views/admin/products/_song_form.html.erb
<td class="song-form col-xs-2">
    <%= f.select :artist_id, @artists.map{|t| [t.name, t.id]},{}, class: 'form-control'  %>
</td>
<td class='song-form col-xs-3'>
    <%= f.file_field :file, class: 'form-control'%>
</td>
<td class='song-form col-xs-2'>
    <%= f.text_field :name, class: 'form-control' %>
</td>
<td class='song-form col-xs-2'>
    <%= f.range_field :recommend_level, class: 'recommend', min: 1, max: 5, step: 1 %>
</td>

app/views/admin/products/_track_relation_form.erb
<tr>
    <td class="col-xs-1"><%= f.number_field :track_order, class: 'form-control', min: 1%></td> 
    <% if controller.action_name == "new" %>
        <%= new_song_field(f, :song, {}) %>
        <td><%= select_song_field("mode:新規曲選択", f, :song, "new",{})%></td>
    <% elsif controller.action_name == "edit" %>
        <%= render "admin/products/select_song_form", f: f%>
        <td><%= select_song_field("mode:既存曲選択", f, :song, "exist",{})%></td>
    <% end %>
    <td class="col-xs-2"><%= link_to_remove_field("track remove", f, :track_relations, {}) %></td>
</tr>

app/views/admin/products/edit.html.erb
<div class="container">
    <% if flash[:alert] %>
        <% flash[:alert].each do |message| %>
            <p class="text-danger">
                <%= message %>
            </p>
        <% end %>
    <% end %>

    <div class="form-horizontal mt-3" role='form'>
        <div class="row">
            <div class="col-xs-8"><h2>商品情報編集</h2></div>
            <div class="col-xs-4"><%= link_to  "一覧に戻る", admin_products_path, class: "btn btn-primary pull-right" %></div>
        </div>
        <div class="row">
        <%= form_for [:admin, @product] do |f| %>
            <div class="form-group">
                <%= f.label :product, :image, class:'control-label' %>
                <%= f.attachment_field :image, placeholder: "ジャケット画像"%>
            </div>
            <div class="form-group">
                <div class='col-xs-2'>
                    <%= f.label :product, :name, class:'control-label' %>
                </div>
                <div class='col-xs-10'>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
            </div>

            <div class="form-group">
                <div class='col-xs-2'>
                    <%= f.label :product, :product_type, class:'control-label' %>
                </div>
                <div class='col-xs-10'>
                    <%= f.select :product_type, [["シングル", 0],["アルバム", 1]],{}, class: 'form-control' %>
                </div>
            </div>

            <div class="form-group">
                <div class='col-xs-2'>
                    <%= f.label :product, :label_id, class:'control-label' %>
                </div>
                <div class='col-xs-10'>
                    <%= f.select :label_id, @labels.map{|t| [t.name, t.id]},{}, class: 'form-control' %>
                </div>
            </div>

            <div class="form-group">
                <div class='col-xs-2'>
                    <%= f.label :product, :genre_id, class:'control-label' %>
                </div>
                <div class='col-xs-10'>
                    <%= f.select :genre_id, @genres.map{|t| [t.name, t.id]},{}, class: 'form-control' %>
                </div>
            </div>

            <div class="form-group">
                <div class='col-xs-2'>
                    <%= f.label :product, :price, class:'control-label' %>
                </div>
                <div class='col-xs-10'>
                    <%= f.number_field :price, class: 'form-control' %>
                </div>
            </div>

            <div class="form-group">
                <div class='col-xs-2'>
                    <%= f.label :product, :release_date, class:'control-label' %>
                </div>
                <div class='col-xs-10'>
                    <%= f.date_select :release_date,{use_month_numbers: true}, {class: 'bootstrap-date'} %>
                </div>
            </div>

            <div class="form-group">
                <%= link_to_add_field("disc add", f, :discs, {}) %>
                <% f.object.discs.each do |disc| %>
                    <%= f.fields_for :discs, disc, child_index: disc.object_id do |builder| %>
                        <%= render "admin/products/disc_form", f: builder %>
                    <% end %>
                <% end %>
            </div>
            
            <div class="actions">
                <%= f.submit "UPDATE", class:"btn btn-primary pull-right" %>
            </div>
        <% end %>
        </div>
    </div>
</div>

app/views/admin/products/index.html.erb
<%= render 'admin/products/product_list', products: @products %>

app/views/admin/products/new.html.erb
<div class="container">
    <% @product.errors.full_messages.each do |message| %>
        <p class="text-danger">
            <%= message %>
        </p>
    <% end %>

    <div class="form-horizontal mt-3" role='form'>
        <div class="row">
            <div class="col-xs-8"><h2>商品情報追加</h2></div>
            <div class="col-xs-4"><%= link_to  "一覧に戻る", admin_products_path, class: "btn btn-primary pull-right" %></div>
        </div>
        <div class="row">
        <%= form_for [:admin, @product] do |f| %>
            <div class="form-group">
                <%= f.label :product, :image, class:'control-label' %>
                <%= f.attachment_field :image, placeholder: "ジャケット画像"%>
            </div>
            <div class="form-group">
                <div class='col-xs-2'>
                    <%= f.label :product, :name, class:'control-label' %>
                </div>
                <div class='col-xs-10'>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
            </div>

            <div class="form-group">
                <div class='col-xs-2'>
                    <%= f.label :product, :product_type, class:'control-label' %>
                </div>
                <div class='col-xs-10'>
                    <%= f.select :product_type, [["シングル", 0],["アルバム", 1]],{}, class: 'form-control' %>
                </div>
            </div>

            <div class="form-group">
                <div class='col-xs-2'>
                    <%= f.label :product, :label_id, class:'control-label' %>
                </div>
                <div class='col-xs-10'>
                    <%= f.select :label_id, @labels.map{|t| [t.name, t.id]},{}, class: 'form-control' %>
                </div>
            </div>

            <div class="form-group">
                <div class='col-xs-2'>
                    <%= f.label :product, :genre_id, class:'control-label' %>
                </div>
                <div class='col-xs-10'>
                    <%= f.select :genre_id, @genres.map{|t| [t.name, t.id]},{}, class: 'form-control' %>
                </div>
            </div>

            <div class="form-group">
                <div class='col-xs-2'>
                    <%= f.label :product, :price, class:'control-label' %>
                </div>
                <div class='col-xs-10'>
                    <%= f.number_field :price, class: 'form-control' %>
                </div>
            </div>

            <div class="form-group">
                <div class='col-xs-2'>
                    <%= f.label :product, :release_date, class:'control-label' %>
                </div>
                <div class='col-xs-10'>
                    <%= f.date_select :release_date,{use_month_numbers: true}, {class: 'bootstrap-date'} %>
                </div>
            </div>

            <div class="form-group">
                <%= link_to_add_field("disc add", f, :discs, {}) %>
            </div>

            <div class="actions">
                <%= f.submit "登録!!", class:"btn btn-primary pull-right" %>
            </div>
        <% end %>
        </div>
    </div>
</div>