config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'users/registrations'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    get '/', to: "tops#index"
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :artists, only: [:index, :show, :create, :edit, :update, :destroy]
    resources :genres, only: [:index, :show, :create, :edit, :update, :destroy]
    resources :labels, only: [:index, :show, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show,  :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update, :destroy]
    resources :contacts, only: [:index, :show, :update]
  end

  scope module: :user do
    root to: "genres#index"
    resources :genres, only: [:show]
    resources :searches, only: [:index, :create]
    resources :songs, only: [:show]
    resources :orders, only: [:index, :new, :create, :update]
    resource :mypages, only: [:show, :edit, :new, :create, :update, :destroy]
    resources :carts, only: [:index, :update, :destroy]
    resource :contacts, only: [:new, :create]
    post 'products/:id/add', to: "products#add", as: "add_cartdetail"
    patch 'mypages/info', to: 'mypages#create_info'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_details, dependent: :destroy
  has_many :orders, dependent: :destroy

  enum admin: { admin: true, customer: false }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::Base
  before_action :authenticate_user!
  authorize_resource

  def index
    @users = User.page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    @orders = Order.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
       redirect_to admin_users_path
      else
        render :edit
      end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit(:state, :city, :address, :name, :name_kana, :postal_code, :tel, :admin)
  end
end

app/controllers/user/base.rb
class User::Base < ApplicationController
     layout 'user'
end

app/controllers/user/carts_controller.rb
class User::CartsController < User::Base
  def index
  	@carts = CartDetail.where(user_id: current_user.id)
  end

  def create
  end

  def update
  	cart = CartDetail.find(params[:id])
  	cart.update(cart_params)
  	redirect_to carts_path
  end

  def destroy
  	cart = CartDetail.find(params[:id])
  	cart.destroy
  	redirect_to carts_path
  end

  private
  	def cart_params
  		params.require(:cart_detail).permit(:user_id, :product_id, :number)
  	end
end

app/controllers/user/contacts_controller.rb
class User::ContactsController < User::Base
  def new
  	@contact = Contact.new
    @non_member = NonMember.new
  end

  def create
    if user_signed_in?
      contact = Contact.new(contact_params)
      contact.user_id = current_user.id
      contact.save!
      redirect_to new_contacts_path,alert: "お問い合わせを受け付けました。"
    else
      non_member = NonMember.new(non_member_params)
      if non_member.save!
         contact = Contact.new(contact_params)
         contact.non_member_id = non_member.id
         contact.save!
         redirect_to new_contacts_path,alert: "お問い合わせを受け付けました。"
      end
    end
  end

  private
  def contact_params
  	params.require(:contact).permit(:title, :body)
  end
  def non_member_params
    params.require(:non_member).permit(:name, :email)
  end


end

app/controllers/user/genres_controller.rb
class User::GenresController < User::Base
	load_and_authorize_resource
  def index
  	@genres = Genre.all
  end

  def show
  	@genre = Genre.find(params[:id])

  	array = []
  	products = Product.where(genre_id: params[:id])
		products.each do |product|
			product.discs.each do |disc|
				disc.track_relations.each do |t|
					array.push(t.song)
				end
			end
		end
		array.uniq!
		@songs = Kaminari.paginate_array(array).page(params[:page]).per(10)
		# per(x)でページごとの表示件数をxに決定

  end
end

app/controllers/user/mypages_controller.rb
class User::MypagesController < User::Base
	def new
		if user_signed_in?
			@info = User.find(current_user.id)
		else
			redirect_to root_path
		end
	end

	def show
		@user = User.find(current_user.id)
	end

	def edit
		@user = User.find(current_user.id)
	end

	def create_info
		info_user = User.find(current_user.id)
		#info_user.address = "#{info_user.state}#{info_user.city}#{info_user.place}"
		if info_user.update(user_params)
		   redirect_to root_path
		else
			render :new
		end

	end

	def update
		@user = User.find(current_user.id)

		if @user.update(user_params)
		   redirect_to mypages_path
	    else
	    	render :edit
	    end
	end

	def destroy
		user = User.find(current_user.id)
		user.destroy
		redirect_to root_path
	end

	def user_params
  	params.require(:user).permit(:state, :city, :address, :name, :name_kana, :postal_code, :tel)
  end
end

app/controllers/user/orders_controller.rb
class User::OrdersController < User::Base
  def index
    @orders = current_user.orders.reverse
  end

  def new
    @cart_details = current_user.cart_details

    @sum = 0
    @cart_details.each do |c|
      @sum += c.product.price * c.number
    end
  end

  def create
      order = Order.new
      order.user_id = current_user.id
      if order.save!
        bool = 0
        current_user.cart_details.each do |c|
          c.product.with_lock do    #悲観的ロック
            if c.product.stock >= c.number
              order_detail = OrderDetail.new
              order_detail.order_id = order.id
              order_detail.product_id = c.product.id
              order_detail.price = c.product.price
              order_detail.number = c.number
              order_detail.save!
              order_detail.product.update(stock: order_detail.product.stock - order_detail.number)
            else
              bool += 1
            end
          end
        end

        if bool == 0
          CartDetail.where(user_id: current_user.id).destroy_all
          redirect_to root_path, notice: "注文を確定しました"
        else
          order.order_details.each do |o|
            o.product.update(stock: o.product.stock + o.number)
          end
          order.destroy
          redirect_to carts_path, notice: "注文に失敗しました"
        end
      else
        redirect_to carts_path, notice: "注文に失敗しました"
      end
  end

  def update
    order = Order.find(params[:id])
    order.update!(cancel_request: true)
    redirect_to orders_path
  end

end

app/controllers/user/products_controller.rb
class User::ProductsController < User::Base
	before_action :authenticate_user!
	def add
		if CartDetail.where(user_id: current_user.id, product_id: params[:id]).present?
			flash[:notice] = "カート内に既に存在しています"
			redirect_to carts_path
		else
			cartd = CartDetail.new(cartd_params)
			cartd.user_id = current_user.id
			cartd.product_id = params[:id]
			if cartd.save
				cartd.product.stock -= cartd.number
				redirect_to carts_path
			else
				redirect_to root_path
			end
		end
 	end

 	private
 		def cartd_params
 			params.permit(:number)
 		end
end

app/controllers/user/searches_controller.rb
class User::SearchesController < User::Base
  def index
  	@sel = params[:sel].to_i
    @keyword = params[:keyword]
  	if @sel == 1
  		#アーティスト
      array = []
  		artists = Artist.where('name LIKE ?', "%#{params[:keyword]}%")
      artists.each do |art|
        songs = Song.where(artist_id: art.id)
        songs.each do |s|
          array << s
        end
      end
      flash[:notice] = "アーティスト名が \"#{@keyword}\" に類似する楽曲を表示します"
      @res = array.uniq
  	elsif @sel == 2
  		#曲名
      flash[:notice] = "曲名が \"#{@keyword}\" に類似する楽曲を表示します"
       @res = Song.where('name LIKE ?', "%#{params[:keyword]}%")
  	elsif @sel == 3
  		#商品名
      array = []
  		products = Product.where('name LIKE ?', "%#{params[:keyword]}%")
      products.each do |pro|
        pro.discs.each do |d|
          d.track_relations.each do |tr|
              array << tr.song
          end
        end
      end
      flash[:notice] = "商品名が \"#{@keyword}\" に類似した商品に含まれる楽曲を表示します"
      @res = array.uniq
  	else
  		redirect_to root_path
  	end
  end

  def create
  	#パラメータからクエリパラメータを含むurlを生成する。
  	arg = {sel: params[:sel], keyword: params[:keyword]}
    redirect_to "/searches?#{arg.to_query}"
  end
end

app/controllers/user/songs_controller.rb
class User::SongsController < User::Base
  def show
  	@track = TrackRelation.find(params[:id])
    track_list = TrackRelation.where(song_id: @track.song_id)

    # queryの曲を含む商品array
    @products = []
    track_list.each do |track|
      p = track.disc.product
      if !@products.include?(p)
        @products << p
      end
    end

  end

end

app/controllers/user/users_controller.rb
class User::UsersController < User::Base
	def show
	end

	def edit
	end

	def update
	end

	def destroy
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def after_inactive_sign_up_path_for (resource)
    new_mypages_path
  end

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
     super(resource)
     new_mypages_path
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/carts_helper.rb
module User::CartsHelper
end

app/views/admin/users/edit.html.erb
<h3 class="text-center">ユーザ情報編集</h3>

<%= form_with model: @user ,url: admin_user_path,method: :patch, class:"form-horizontal"  do |f| %>
  <div class="form-group pt pb">
    <%= f.label :"E-mail", class: "col-xs-3 control-label"  %>
    <div class="col-xs-6"><%= f.email_field :email, class: "form-control" %></div>
  </div>
  <div class="form-group pt pb">
    <%= f.label :"氏名", class: "col-xs-3 control-label"  %>
    <div class="col-xs-6"><%= f.text_field :name, class: "form-control" %></div>
  </div>
  <div class="form-group pt pb">
    <%= f.label :"フリガナ", class: "col-xs-3 control-label"  %>
    <div class="col-xs-6"><%= f.text_field :name_kana, class: "form-control" %></div>
  </div>
  <div class="form-group pt pb">
    <%= f.label :"郵便番号", class: "col-xs-3 control-label"  %>
    <div class="col-xs-6"><%= f.text_field :postal_code, class: "form-control" %></div>
  </div>
  <div class="form-group pt pb">
    <%= f.label :"都道府県", class: "col-xs-3 control-label"  %>
    <div class="col-xs-6"><%= f.text_field :state, class: "form-control" %></div>
  </div>
  <div class="form-group pt pb">
    <%= f.label :"市区町村", class: "col-xs-3 control-label"  %>
    <div class="col-xs-6"><%= f.text_field :city, class: "form-control" %></div>
  </div>
  <div class="form-group pt pb">
    <%= f.label :"住所", class: "col-xs-3 control-label"  %>
    <div class="col-xs-6"><%= f.text_field :address, class: "form-control" %></div>
  </div>
  <div class="form-group pt pb">
    <%= f.label :"電話番号", class: "col-xs-3 control-label"  %>
    <div class="col-xs-6"><%= f.text_field :tel, class: "form-control" %></div>
  </div>
  <% if @user.id != current_user.id %>
    <div class="form-group pt pb">
      <%= f.label :"管理者権限", class: "col-xs-3 control-label"  %>
      <div class="col-xs-3"><%= f.select :admin, User.admins.keys.to_a, {}, class: "form-control" %></div>
      <div class="col-xs-6"></div>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit "変更", class:"btn btn-warning" %>
  </div>
  <div class="col-xs-8 col-xs-offset-2 mt mb">
    <%= link_to admin_users_path do %>
      <button type="button" class="btn btn-default pull-right">戻る</button>
    <% end %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<h3>顧客一覧</h3>
<p class="text-info">現在ログインしている管理者ユーザ名: <%= current_user.name %></p>

<table class="table">
	<tr>
		<td class="col-xs-1"> 顧客ID</td>
		<td class="col-xs-2"> 氏名</td>
		<td class="col-xs-2"> 氏名カナ</td>
		<td class="col-xs-2"> 権限</td>
		<td class="col-xs-1""></td>
		<td class="col-xs-1""></td>
		<td class="col-xs-1""></td>
	</tr>
	<% @users.each do |user| %>
		<tr>
			<td> <%= user.id %></td>
			<td> <%= user.name %></td>
			<td> <%= user.name_kana %></td>
			<td> <%= user.admin %></td>
			<td> <%= link_to admin_user_path(user) do %> <button type="button" class="btn btn-primary">詳細</button><% end %></td>
			<td> <%= link_to edit_admin_user_path(user) do %> <button type="button" class="btn btn-success">編集</button><% end %></td>
			<td> <%= link_to admin_user_path(user), method: :delete, "data-confirm" => "本当に削除しますか？" do %> <button type="button" class="btn btn-danger">削除</button><% end %></td>
		</tr>
	<% end %>
</table>
<%= paginate @users, class: "paginate" %>

app/views/admin/users/show.html.erb
<div class="container mt mb ">
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<h2> User詳細</h2>

			<table class="table">
				<tr>
					<td class="col-xs-3"> 氏名</td>
					<td class="col-xs-9"> <%= @user.name %></td>
				</tr>
				<tr>
					<td class="col-xs-3"> 氏名カナ</td>
					<td class="col-xs-9"> <%= @user.name_kana %></td>
				</tr>
				<tr>
					<td class="col-xs-3"> 郵便番号</td>
					<td class="col-xs-9"> <%= @user.postal_code %></td>
				</tr>
				<tr>
					<td class="col-xs-3"> 住所</td>
					<td class="col-xs-9"> <%= @user.address %></td>
				</tr>
				<tr>
					<td class="col-xs-3"> tel</td>
					<td class="col-xs-9"> <%= @user.tel %></td>
				</tr>
				<tr>
					<td class="col-xs-3"> e-mail</td>
					<td class="col-xs-9"> <%= @user.email %></td>
				</tr>
				<tr>
					<td class="col-xs-3"> 管理者権限</td>
					<td class="col-xs-9"> <% if @user.admin %> 管理者<% else %> ユーザ<% end %></td>
				</tr>
			</table>

			<hr style="margin: 60px 0">

			<h3> 注文一覧</h3>
			<table class="table">
				<thead>
					<th class="col-xs-2"> 注文ID</th>
					<th class="col-xs-2"> 注文日時</th>
					<th class="col-xs-2"> 発送状態</th>
					<th class="col-xs-2"> キャンセル状態</th>
					<th class="col-xs-2"></th>
					<th class="col-xs-2"></th>
				</thead>
				<tbody>
				<% @orders.each do |order| %>
					<tr>
						<td> <%= order.id %></td>
						<td> <%= simple_time(order.created_at) %></td>
						<td>
							<%= form_for [:admin, order] do |f| %>
								<%= f.select :shipment_status, options_for_select({"準備中": 0, "発送済": 1, "到着済": 2}, order.shipment_status), {}, onchange: "javascript: this.form.submit();" %>
							<% end %>
						</td>
						<td> <% if order.cancel_request %> <span style="color: red"> キャンセル</span>
								<% else %> 未<% end %> </td>
						<td> <%= link_to admin_order_path(order) do %> <button type="button" class="btn btn-primary btn-xs">詳細</button><% end %></td>
						<td> <%= link_to admin_order_path(order), method: :delete, "data-confirm" => "本当に削除しますか？" do %> <button type="button" class="btn btn-danger btn-xs">削除</button><% end %></td>
					</tr>
				<% end %>
				</tbody>
			</table>
			<div class="mt mb">
				<%=link_to "戻る", admin_users_path, class: :"btn btn-default pull-right" %>
			</div>
		</div>
	</div>
</div>